### ISSUE TITLE
Problem running web server

### ISSUE THREAD

**Issue by mehdibo** [kenanEkici/pepper-google-assistant#4]
When I run `FLASK_APP=webserver.py flask run` on my computer, I get this error:
```
 * Serving Flask app "webserver.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "pepper-google-assistant.webserver", an ImportError was raised:

Traceback (most recent call last):
  File "/home/spoody/Projects/pepper-google-assistant/env/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/spoody/Projects/pepper-google-assistant/webserver.py", line 8, in <module>
    from naoqi import ALProxy
ModuleNotFoundError: No module named 'naoqi'
```

**Comment by kenanEkici** [comment]
Hi, sorry for the late reply. Have you installed the Naoqi Python package? It includes the Proxy needed to connect with the Pepper or Naoqi robot. You can follow more instructions at http://doc.aldebaran.com/2-5/dev/python/install_guide.html
